services:
  pgadmin:
    image: dpage/pgadmin4:9.2
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "10001:80"
    networks:
      - nuance

networks:
  nuance:
    external: true