[project]
name = "nuance"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "asyncpg>=0.30.0",
    "bittensor>=9.1.0",
    "loguru>=0.7.3",
    "pydantic-settings>=2.8.1",
    "sqlalchemy>=2.0.40",
]
